# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: kindlemail 0.2.8 ruby lib

Gem::Specification.new do |s|
  s.name = "kindlemail"
  s.version = "0.2.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Daniel Harper"]
  s.date = "2014-12-19"
  s.description = "Sends documents to a designated kindle address painlessly and via the CLI. No need to fumble around with clumsy attachment boxes so forth, just whack in the documents you want to send and hit enter"
  s.email = "djharperuk@gmail.com"
  s.executables = ["kindlemail"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Changelog.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "TODO.txt",
    "VERSION",
    "bin/kindlemail",
    "conf_templates/.email_conf",
    "conf_templates/.kindlemail",
    "kindlemail.gemspec",
    "lib/Configuration.rb",
    "lib/KindleMail.rb",
    "lib/KindleMailFileDatastore.rb",
    "lib/KindleMailer.rb",
    "lib/constants.rb",
    "test/test_kindle_mailer.rb"
  ]
  s.homepage = "http://github.com/djhworld/kindlemail"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Push documents to your kindle via the personal document service"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<gmail-mailer>, [">= 0"])
      s.add_development_dependency(%q<trollop>, [">= 0"])
      s.add_runtime_dependency(%q<gmail-mailer>, [">= 0"])
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gmail-mailer>, [">= 0"])
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<gmail-mailer>, [">= 0"])
      s.add_dependency(%q<trollop>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gmail-mailer>, [">= 0"])
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<gmail-mailer>, [">= 0"])
    s.add_dependency(%q<trollop>, [">= 0"])
  end
end

